/* eslint-disable */
// AUTO-GENERATED by scripts/wp-import/redirect-map-regenerate.ts.
// Do not edit by hand. Run `npm run redirect-map:regenerate` to refresh.
//
// Source of truth: migration/redirect-map.csv.
// Imported by next.config.ts to populate `async redirects()`.

export interface RedirectRule {
  source: string;
  destination: string;
  permanent: boolean;
}

export const redirects: RedirectRule[] = [
  {
    "source": "/fi/egyptin-hieroglyfien-ymmartaminen",
    "destination": "/",
    "permanent": true
  },
  {
    "source": "/nile-cruise-holidays",
    "destination": "/nile-cruises/nile-cruise-holidays",
    "permanent": true
  },
  {
    "source": "/es/vacaciones-en-un-crucero-por-el-nilo",
    "destination": "/es/nile-cruises/vacaciones-en-un-crucero-por-el-nilo",
    "permanent": true
  },
  {
    "source": "/ja/ナイルクルーズの休日",
    "destination": "/ja/nile-cruises/ナイルクルーズの休日",
    "permanent": true
  },
  {
    "source": "/fi/boutique-niilin-risteilyt",
    "destination": "/",
    "permanent": true
  },
  {
    "source": "/fi/kuinka-valita-sim-kortti-egyptin-matkalle",
    "destination": "/",
    "permanent": true
  },
  {
    "source": "/fi/suuren-gizan-pyramidin-sisaan",
    "destination": "/",
    "permanent": true
  },
  {
    "source": "/m-s-amwaj-livingstone-nile-cruise",
    "destination": "/nile-cruises/m-s-amwaj-livingstone-nile-cruise",
    "permanent": true
  },
  {
    "source": "/es/m-s-amwaj-livingstone",
    "destination": "/es/nile-cruises/m-s-amwaj-livingstone",
    "permanent": true
  },
  {
    "source": "/ja/m-s-アムワジ・リビングストン",
    "destination": "/ja/nile-cruises/m-s-アムワジ・リビングストン",
    "permanent": true
  },
  {
    "source": "/es/m-s-al-kahila-crucero-por-el-nilo",
    "destination": "/es/nile-cruises/m-s-al-kahila-crucero-por-el-nilo",
    "permanent": true
  },
  {
    "source": "/ja/m-s-アル・ジャミラ・ナイル・クルーズ（m-s-al-jamila-nile-cruise）",
    "destination": "/ja/nile-cruises/m-s-アル・ジャミラ・ナイル・クルーズ（m-s-al-jamila-nile-cruise）",
    "permanent": true
  },
  {
    "source": "/m-s-nubian-sea",
    "destination": "/nile-cruises/m-s-nubian-sea",
    "permanent": true
  },
  {
    "source": "/ja/m-s-ヌビアン・シー（m-s-nubian-sea）",
    "destination": "/ja/nile-cruises/m-s-ヌビアン・シー（m-s-nubian-sea）",
    "permanent": true
  },
  {
    "source": "/agatha-dahabiya",
    "destination": "/nile-cruises/agatha-dahabiya",
    "permanent": true
  },
  {
    "source": "/es/agatha-dahabiya",
    "destination": "/es/nile-cruises/agatha-dahabiya",
    "permanent": true
  },
  {
    "source": "/ja/アガサ・ダハビヤ（agatha-dahabiya）",
    "destination": "/ja/nile-cruises/アガサ・ダハビヤ（agatha-dahabiya）",
    "permanent": true
  },
  {
    "source": "/fi/kuinka-pukeutua-vieraillessa-egyptissa",
    "destination": "/",
    "permanent": true
  },
  {
    "source": "/ms-esplanade-nile-cruise",
    "destination": "/nile-cruises/ms-esplanade-nile-cruise",
    "permanent": true
  },
  {
    "source": "/es/ms-esplanade-nile-cruise",
    "destination": "/es/nile-cruises/ms-esplanade-nile-cruise",
    "permanent": true
  },
  {
    "source": "/ja/m-s-エスプラナード・ナイル・クルーズ（m-s-esplanade-nile-cruise）",
    "destination": "/ja/nile-cruises/m-s-エスプラナード・ナイル・クルーズ（m-s-esplanade-nile-cruise）",
    "permanent": true
  },
  {
    "source": "/m-s-al-kahila-nile-cruise",
    "destination": "/nile-cruises/m-s-al-kahila-nile-cruise",
    "permanent": true
  },
  {
    "source": "/ja/m-s-ソネスタ・ムーン・ゴッデス",
    "destination": "/ja/nile-cruises/m-s-ソネスタ・ムーン・ゴッデス",
    "permanent": true
  },
  {
    "source": "/es/m-s-al-jamila-crucero-por-el-nilo",
    "destination": "/es/nile-cruises/m-s-al-jamila-crucero-por-el-nilo",
    "permanent": true
  },
  {
    "source": "/ja/m-s-メイフェア・ナイル・クルーズ（m-s-mayfair-nile-cruise）",
    "destination": "/ja/nile-cruises/m-s-メイフェア・ナイル・クルーズ（m-s-mayfair-nile-cruise）",
    "permanent": true
  },
  {
    "source": "/ja/オベロイ・ザフラ・ナイル・クルーズ（oberoi-zahra-nile-cruise）",
    "destination": "/ja/nile-cruises/オベロイ・ザフラ・ナイル・クルーズ（oberoi-zahra-nile-cruise）",
    "permanent": true
  },
  {
    "source": "/meroe-dahabiya",
    "destination": "/nile-cruises/meroe-dahabiya",
    "permanent": true
  },
  {
    "source": "/es/meroe-dahabiya",
    "destination": "/es/nile-cruises/meroe-dahabiya",
    "permanent": true
  },
  {
    "source": "/ja/メロエ・ダハビヤ",
    "destination": "/ja/nile-cruises/メロエ・ダハビヤ",
    "permanent": true
  },
  {
    "source": "/m-s-moon-goddess-nile-cruise",
    "destination": "/nile-cruises/m-s-moon-goddess-nile-cruise",
    "permanent": true
  },
  {
    "source": "/es/m-s-sonesta-diosa-de-la-luna",
    "destination": "/es/nile-cruises/m-s-sonesta-diosa-de-la-luna",
    "permanent": true
  },
  {
    "source": "/the-nile-goddess-cruise",
    "destination": "/nile-cruises/the-nile-goddess-cruise",
    "permanent": true
  },
  {
    "source": "/es/el-crucero-de-la-diosa-del-nilo",
    "destination": "/es/nile-cruises/el-crucero-de-la-diosa-del-nilo",
    "permanent": true
  },
  {
    "source": "/ja/ナイル・ゴッデス・クルーズ",
    "destination": "/ja/nile-cruises/ナイル・ゴッデス・クルーズ",
    "permanent": true
  },
  {
    "source": "/fi/liikkuminen-egyptissa",
    "destination": "/",
    "permanent": true
  },
  {
    "source": "/roman-dahabiya",
    "destination": "/nile-cruises/roman-dahabiya",
    "permanent": true
  },
  {
    "source": "/es/roman-dahabiya",
    "destination": "/es/nile-cruises/roman-dahabiya",
    "permanent": true
  },
  {
    "source": "/ja/ローマン・ダハビヤ（roman-dahabiya）",
    "destination": "/ja/nile-cruises/ローマン・ダハビヤ（roman-dahabiya）",
    "permanent": true
  },
  {
    "source": "/movenpick-sb-feddya-dahabiya",
    "destination": "/nile-cruises/movenpick-sb-feddya-dahabiya",
    "permanent": true
  },
  {
    "source": "/es/movenpick-sb-feddya-dahabiya",
    "destination": "/es/nile-cruises/movenpick-sb-feddya-dahabiya",
    "permanent": true
  },
  {
    "source": "/ja/sb-フェディヤ・ダハビヤ（sb-feddya-dahabiya）",
    "destination": "/ja/nile-cruises/sb-フェディヤ・ダハビヤ（sb-feddya-dahabiya）",
    "permanent": true
  },
  {
    "source": "/nour-el-nil-assouan-dahabiya",
    "destination": "/nile-cruises/nour-el-nil-assouan-dahabiya",
    "permanent": true
  },
  {
    "source": "/es/nour-el-nil-assouan-dahabiya",
    "destination": "/es/nile-cruises/nour-el-nil-assouan-dahabiya",
    "permanent": true
  },
  {
    "source": "/ja/ヌール・エル・ニール・アスワン・ダハビーヤ",
    "destination": "/ja/nile-cruises/ヌール・エル・ニール・アスワン・ダハビーヤ",
    "permanent": true
  },
  {
    "source": "/oberoi-zahra-nile-cruise",
    "destination": "/nile-cruises/oberoi-zahra-nile-cruise",
    "permanent": true
  },
  {
    "source": "/es/oberoi-zahra-nile-cruise",
    "destination": "/es/nile-cruises/oberoi-zahra-nile-cruise",
    "permanent": true
  },
  {
    "source": "/ja/m-s-アル・カヒラ・ナイル・クルーズ（m-s-al-kahila-nile-cruise）",
    "destination": "/ja/nile-cruises/m-s-アル・カヒラ・ナイル・クルーズ（m-s-al-kahila-nile-cruise）",
    "permanent": true
  },
  {
    "source": "/ja/m-s-ソネスタ・スター・ゴッデス（m-s-sonesta-star-goddess）",
    "destination": "/ja/nile-cruises/m-s-ソネスタ・スター・ゴッデス（m-s-sonesta-star-goddess）",
    "permanent": true
  },
  {
    "source": "/es/m-s-omar-el-khayam",
    "destination": "/es/nile-cruises/m-s-omar-el-khayam",
    "permanent": true
  },
  {
    "source": "/fi/sphinxes-and-obelisks-how-egypts-silent-giants-still-speak-today",
    "destination": "/",
    "permanent": true
  },
  {
    "source": "/m-s-sonesta-st-george-nile-cruise",
    "destination": "/nile-cruises/m-s-sonesta-st-george-nile-cruise",
    "permanent": true
  },
  {
    "source": "/es/m-s-sonesta-st",
    "destination": "/es/nile-cruises/m-s-sonesta-st",
    "permanent": true
  },
  {
    "source": "/m-s-steigenberger-omar-el-khayam",
    "destination": "/nile-cruises/m-s-steigenberger-omar-el-khayam",
    "permanent": true
  },
  {
    "source": "/ja/m-s-オマール・エル・ハイヤム（m-s-omar-el-khayam）",
    "destination": "/ja/nile-cruises/m-s-オマール・エル・ハイヤム（m-s-omar-el-khayam）",
    "permanent": true
  },
  {
    "source": "/nour-el-nil-meroe-dahabiya",
    "destination": "/nile-cruises/nour-el-nil-meroe-dahabiya",
    "permanent": true
  },
  {
    "source": "/es/nour-el-nil-meroe-dahabiya",
    "destination": "/es/nile-cruises/nour-el-nil-meroe-dahabiya",
    "permanent": true
  },
  {
    "source": "/fi/taydellinen-opas-kairon-nmeciin-egyptilaisen-sivilisaation-kansallismuseo",
    "destination": "/",
    "permanent": true
  },
  {
    "source": "/fi/paikalliset-sairaalat-egyptissa",
    "destination": "/",
    "permanent": true
  },
  {
    "source": "/fi/missa-tutankhamun-on-nyt",
    "destination": "/",
    "permanent": true
  },
  {
    "source": "/agatha-dahabiya-journey-along-the-nile",
    "destination": "/nile-cruises/agatha-dahabiya-journey-along-the-nile",
    "permanent": true
  },
  {
    "source": "/es/el-agatha-dahabiya-descubriendo-el-rio-eterno-de-egipto",
    "destination": "/es/nile-cruises/el-agatha-dahabiya-descubriendo-el-rio-eterno-de-egipto",
    "permanent": true
  },
  {
    "source": "/ja/アガサ・ダハビーヤ：ナイル川をたどる旅",
    "destination": "/ja/nile-cruises/アガサ・ダハビーヤ：ナイル川をたどる旅",
    "permanent": true
  },
  {
    "source": "/adelaide-dahabiya-nile-cruise",
    "destination": "/nile-cruises/adelaide-dahabiya-nile-cruise",
    "permanent": true
  },
  {
    "source": "/es/descubriendo-el-nilo-un-viaje-a-bordo-del-adelaide-dahabiya",
    "destination": "/es/nile-cruises/descubriendo-el-nilo-un-viaje-a-bordo-del-adelaide-dahabiya",
    "permanent": true
  },
  {
    "source": "/ja/ナイル探求の旅：アデライード・ダハビーヤ号で",
    "destination": "/ja/nile-cruises/ナイル探求の旅：アデライード・ダハビーヤ号で",
    "permanent": true
  },
  {
    "source": "/adelaide-dahabiya",
    "destination": "/nile-cruises/adelaide-dahabiya",
    "permanent": true
  },
  {
    "source": "/es/adelaide-dahabiya",
    "destination": "/es/nile-cruises/adelaide-dahabiya",
    "permanent": true
  },
  {
    "source": "/ja/アデライド・ダハビヤ（adelaide-dahabiya）",
    "destination": "/ja/nile-cruises/アデライド・ダハビヤ（adelaide-dahabiya）",
    "permanent": true
  },
  {
    "source": "/authentic-dahabiya-nile-cruise",
    "destination": "/nile-cruises/authentic-dahabiya-nile-cruise",
    "permanent": true
  },
  {
    "source": "/es/crucero-dahabiya-por-el-nilo",
    "destination": "/es/nile-cruises/crucero-dahabiya-por-el-nilo",
    "permanent": true
  },
  {
    "source": "/ja/ダハビーヤ・ナイルクルーズ",
    "destination": "/ja/nile-cruises/ダハビーヤ・ナイルクルーズ",
    "permanent": true
  },
  {
    "source": "/nour-el-nil-malouka-dahabiya",
    "destination": "/nile-cruises/nour-el-nil-malouka-dahabiya",
    "permanent": true
  },
  {
    "source": "/es/nour-el-nil-malouka-dahabiya",
    "destination": "/es/nile-cruises/nour-el-nil-malouka-dahabiya",
    "permanent": true
  },
  {
    "source": "/el-nil-dahabiya",
    "destination": "/nile-cruises/el-nil-dahabiya",
    "permanent": true
  },
  {
    "source": "/es/el-nil-dahabiya",
    "destination": "/es/nile-cruises/el-nil-dahabiya",
    "permanent": true
  },
  {
    "source": "/ja/エル・ニル・ダハビヤ",
    "destination": "/ja/nile-cruises/エル・ニル・ダハビヤ",
    "permanent": true
  },
  {
    "source": "/m-s-historia-nile-cruise",
    "destination": "/nile-cruises/m-s-historia-nile-cruise",
    "permanent": true
  },
  {
    "source": "/es/crucero-por-el-nilo-m-s-historia",
    "destination": "/es/nile-cruises/crucero-por-el-nilo-m-s-historia",
    "permanent": true
  },
  {
    "source": "/m-s-mayfair",
    "destination": "/nile-cruises/m-s-mayfair",
    "permanent": true
  },
  {
    "source": "/es/m-s-mayfair-crucero-por-el-nilo",
    "destination": "/es/nile-cruises/m-s-mayfair-crucero-por-el-nilo",
    "permanent": true
  },
  {
    "source": "/m-s-mayflower-nile-cruise",
    "destination": "/nile-cruises/m-s-mayflower-nile-cruise",
    "permanent": true
  },
  {
    "source": "/es/m-s-mayflower-nile-cruise",
    "destination": "/es/nile-cruises/m-s-mayflower-nile-cruise",
    "permanent": true
  },
  {
    "source": "/ja/m-sメイフラワー・ナイルクルーズ",
    "destination": "/ja/nile-cruises/m-sメイフラワー・ナイルクルーズ",
    "permanent": true
  },
  {
    "source": "/m-s-sonesta-star-goddess-nile-cruise",
    "destination": "/nile-cruises/m-s-sonesta-star-goddess-nile-cruise",
    "permanent": true
  },
  {
    "source": "/es/m-s-sonesta-star-goddess",
    "destination": "/es/nile-cruises/m-s-sonesta-star-goddess",
    "permanent": true
  },
  {
    "source": "/m-s-alexander-the-great-nile-cruise",
    "destination": "/nile-cruises/m-s-alexander-the-great-nile-cruise",
    "permanent": true
  },
  {
    "source": "/es/y-s-alejandro-magno",
    "destination": "/es/nile-cruises/y-s-alejandro-magno",
    "permanent": true
  },
  {
    "source": "/ja/y-s-アレクサンダー・ザ・グレート（y-s-alexander-the-great）",
    "destination": "/ja/nile-cruises/y-s-アレクサンダー・ザ・グレート（y-s-alexander-the-great）",
    "permanent": true
  },
  {
    "source": "/m-s-steigenberger-legacy-nile-cruise",
    "destination": "/nile-cruises/m-s-steigenberger-legacy-nile-cruise",
    "permanent": true
  },
  {
    "source": "/es/m-s-steigenberger-legacy-nile-cruise",
    "destination": "/es/nile-cruises/m-s-steigenberger-legacy-nile-cruise",
    "permanent": true
  },
  {
    "source": "/ja/m-s-シュタイゲンベルガー・レガシー（m-s-steigenberger-legacy）",
    "destination": "/ja/nile-cruises/m-s-シュタイゲンベルガー・レガシー（m-s-steigenberger-legacy）",
    "permanent": true
  },
  {
    "source": "/movenpick-ms-sun-ray-nile-cruise",
    "destination": "/nile-cruises/movenpick-ms-sun-ray-nile-cruise",
    "permanent": true
  },
  {
    "source": "/es/movenpick-m-s-sun-ray",
    "destination": "/es/nile-cruises/movenpick-m-s-sun-ray",
    "permanent": true
  },
  {
    "source": "/ja/モーヴェンピック-m-s-サン・レイ（movenpick-m-s-sun-ray）",
    "destination": "/ja/nile-cruises/モーヴェンピック-m-s-サン・レイ（movenpick-m-s-sun-ray）",
    "permanent": true
  },
  {
    "source": "/movenpick-ms-royal-lotus-nile-cruise",
    "destination": "/nile-cruises/movenpick-ms-royal-lotus-nile-cruise",
    "permanent": true
  },
  {
    "source": "/es/movenpick-ms-royal-lotus-nile-cruise",
    "destination": "/es/nile-cruises/movenpick-ms-royal-lotus-nile-cruise",
    "permanent": true
  },
  {
    "source": "/ja/モーヴェンピック-m-s-ロイヤル・ロータス（movenpick-m-s-royal-lotus",
    "destination": "/ja/nile-cruises/モーヴェンピック-m-s-ロイヤル・ロータス（movenpick-m-s-royal-lotus",
    "permanent": true
  },
  {
    "source": "/movenpick-ms-darakum-nile-cruise",
    "destination": "/nile-cruises/movenpick-ms-darakum-nile-cruise",
    "permanent": true
  },
  {
    "source": "/es/movenpick-ms-darakum-nile-cruise",
    "destination": "/es/nile-cruises/movenpick-ms-darakum-nile-cruise",
    "permanent": true
  },
  {
    "source": "/ja/モーヴェンピック-m-s-ダラクム（movenpick-m-s-darakum）",
    "destination": "/ja/nile-cruises/モーヴェンピック-m-s-ダラクム（movenpick-m-s-darakum）",
    "permanent": true
  },
  {
    "source": "/movenpick-ms-hamees-nile-cruise",
    "destination": "/nile-cruises/movenpick-ms-hamees-nile-cruise",
    "permanent": true
  },
  {
    "source": "/es/movenpick-ms-hamees-nile-cruise",
    "destination": "/es/nile-cruises/movenpick-ms-hamees-nile-cruise",
    "permanent": true
  },
  {
    "source": "/ja/モーヴェンピック-m-s-ハミーズ（movenpick-m-s-hamees）",
    "destination": "/ja/nile-cruises/モーヴェンピック-m-s-ハミーズ（movenpick-m-s-hamees）",
    "permanent": true
  },
  {
    "source": "/m-s-al-jamila-nile-cruise",
    "destination": "/nile-cruises/m-s-al-jamila-nile-cruise",
    "permanent": true
  },
  {
    "source": "/m-s-steigenberger-minerva-nile-cruise",
    "destination": "/nile-cruises/m-s-steigenberger-minerva-nile-cruise",
    "permanent": true
  },
  {
    "source": "/es/crucero-por-el-nilo-m-s-minerva",
    "destination": "/es/nile-cruises/crucero-por-el-nilo-m-s-minerva",
    "permanent": true
  },
  {
    "source": "/ja/m-s-ミネルヴァ・ナイル・クルーズ",
    "destination": "/ja/nile-cruises/m-s-ミネルヴァ・ナイル・クルーズ",
    "permanent": true
  },
  {
    "source": "/movenpick-prince-abbas-cruise",
    "destination": "/nile-cruises/movenpick-prince-abbas-cruise",
    "permanent": true
  },
  {
    "source": "/es/movenpick-prince-abbas-cruise",
    "destination": "/es/nile-cruises/movenpick-prince-abbas-cruise",
    "permanent": true
  },
  {
    "source": "/ja/モーヴェンピック・プリンス・アッバス",
    "destination": "/ja/nile-cruises/モーヴェンピック・プリンス・アッバス",
    "permanent": true
  },
  {
    "source": "/kasr-ibrim-cruise-ship",
    "destination": "/nile-cruises/kasr-ibrim-cruise-ship",
    "permanent": true
  },
  {
    "source": "/es/crucero-kasr-ibrim",
    "destination": "/es/nile-cruises/crucero-kasr-ibrim",
    "permanent": true
  },
  {
    "source": "/ja/カスル・イブリム・クルーズ・シップ",
    "destination": "/ja/nile-cruises/カスル・イブリム・クルーズ・シップ",
    "permanent": true
  },
  {
    "source": "/malouka-dahabiya",
    "destination": "/nile-cruises/malouka-dahabiya",
    "permanent": true
  },
  {
    "source": "/es/malouka-dahabiya",
    "destination": "/es/nile-cruises/malouka-dahabiya",
    "permanent": true
  },
  {
    "source": "/ja/マルーカ・ダハビヤ（malouka-dahabiya）",
    "destination": "/ja/nile-cruises/マルーカ・ダハビヤ（malouka-dahabiya）",
    "permanent": true
  },
  {
    "source": "/sonesta-amirat-dahabiya",
    "destination": "/nile-cruises/sonesta-amirat-dahabiya",
    "permanent": true
  },
  {
    "source": "/es/sonesta-amirat-dahabiya",
    "destination": "/es/nile-cruises/sonesta-amirat-dahabiya",
    "permanent": true
  },
  {
    "source": "/ja/amirat-dahabiya（アミラート",
    "destination": "/ja/nile-cruises/amirat-dahabiya（アミラート",
    "permanent": true
  },
  {
    "source": "/swiss-inn-radamis-ii-nile-cruise",
    "destination": "/nile-cruises/swiss-inn-radamis-ii-nile-cruise",
    "permanent": true
  },
  {
    "source": "/es/posada-suiza-radamis-ii",
    "destination": "/es/nile-cruises/posada-suiza-radamis-ii",
    "permanent": true
  },
  {
    "source": "/ja/スイス・イン・ラダミスii号",
    "destination": "/ja/nile-cruises/スイス・イン・ラダミスii号",
    "permanent": true
  },
  {
    "source": "/m-s-nubian-sea-lake-nasser-cruise",
    "destination": "/nile-cruises/m-s-nubian-sea-lake-nasser-cruise",
    "permanent": true
  },
  {
    "source": "/es/m-s-mar-nubio-lago-nasser",
    "destination": "/es/nile-cruises/m-s-mar-nubio-lago-nasser",
    "permanent": true
  },
  {
    "source": "/ja/m-s-ヌビアン・シー・レイク・ナセル",
    "destination": "/ja/nile-cruises/m-s-ヌビアン・シー・レイク・ナセル",
    "permanent": true
  },
  {
    "source": "/why-choose-us",
    "destination": "/about",
    "permanent": true
  },
  {
    "source": "/only-here-in-cairo",
    "destination": "/guide/cairo/only-here-in-cairo",
    "permanent": true
  },
  {
    "source": "/the-small-temple-of-abu-simbel",
    "destination": "/guide/abu-simbel/the-small-temple-of-abu-simbel",
    "permanent": true
  },
  {
    "source": "/qasr-ibrim",
    "destination": "/guide/abu-simbel",
    "permanent": true
  },
  {
    "source": "/only-in-abu-simbel",
    "destination": "/guide/abu-simbel/only-in-abu-simbel",
    "permanent": true
  },
  {
    "source": "/top-tours-in-abu-simbel",
    "destination": "/guide/abu-simbel",
    "permanent": true
  },
  {
    "source": "/top-hotels-in-abu-simbel",
    "destination": "/guide/abu-simbel/top-hotels-in-abu-simbel",
    "permanent": true
  },
  {
    "source": "/how-to-go-in-abu-simbel",
    "destination": "/guide/abu-simbel/how-to-go-in-abu-simbel",
    "permanent": true
  },
  {
    "source": "/only-in-akhmim",
    "destination": "/guide/akhmim/only-in-akhmim",
    "permanent": true
  },
  {
    "source": "/unique-sites-in-akhmim",
    "destination": "/guide/akhmim/unique-sites-in-akhmim",
    "permanent": true
  },
  {
    "source": "/kom-ushim-karanis",
    "destination": "/guide/al-fayoum",
    "permanent": true
  },
  {
    "source": "/medinet-madi",
    "destination": "/guide/al-fayoum",
    "permanent": true
  },
  {
    "source": "/al-fayoum-waterwheels",
    "destination": "/guide/al-fayoum/al-fayoum-waterwheels",
    "permanent": true
  },
  {
    "source": "/biahmu",
    "destination": "/guide/al-fayoum",
    "permanent": true
  },
  {
    "source": "/only-here-in-al-fayoum",
    "destination": "/guide/al-fayoum/only-here-in-al-fayoum",
    "permanent": true
  },
  {
    "source": "/bardawil-lake",
    "destination": "/guide/al-arish",
    "permanent": true
  },
  {
    "source": "/the-ancient-city-of-pelusium",
    "destination": "/guide/al-arish",
    "permanent": true
  },
  {
    "source": "/the-protected-area-of-zaranik",
    "destination": "/guide/al-arish",
    "permanent": true
  },
  {
    "source": "/only-in-al-arish",
    "destination": "/guide/al-arish/only-in-al-arish",
    "permanent": true
  },
  {
    "source": "/the-fortress-of-al-arish",
    "destination": "/guide/al-arish/the-fortress-of-al-arish",
    "permanent": true
  },
  {
    "source": "/el-ashmunein",
    "destination": "/guide/al-minya",
    "permanent": true
  },
  {
    "source": "/tal-el-amarna",
    "destination": "/guide/al-minya",
    "permanent": true
  },
  {
    "source": "/tuna-el-gebel",
    "destination": "/guide/al-minya",
    "permanent": true
  },
  {
    "source": "/beni-hassan",
    "destination": "/guide/al-minya",
    "permanent": true
  },
  {
    "source": "/tihna-el-gebel",
    "destination": "/guide/al-minya",
    "permanent": true
  },
  {
    "source": "/top-restaurants-in-al-minya",
    "destination": "/guide/al-minya/top-restaurants-in-al-minya",
    "permanent": true
  },
  {
    "source": "/only-here-in-al-minya",
    "destination": "/guide/al-minya/only-here-in-al-minya",
    "permanent": true
  },
  {
    "source": "/getting-around-in-al-minya",
    "destination": "/guide/al-minya/getting-around-in-al-minya",
    "permanent": true
  },
  {
    "source": "/only-here-in-al-quseir",
    "destination": "/guide/al-quseir/only-here-in-al-quseir",
    "permanent": true
  },
  {
    "source": "/the-port-of-myos-hormos",
    "destination": "/guide/al-quseir",
    "permanent": true
  },
  {
    "source": "/bir-umm-fawakhir",
    "destination": "/guide/al-quseir",
    "permanent": true
  },
  {
    "source": "/how-to-get-around-wadi-el-natrun",
    "destination": "/guide/wadi-al-natron",
    "permanent": true
  },
  {
    "source": "/where-to-eat-in-wadi-el-natrun",
    "destination": "/guide/wadi-al-natron",
    "permanent": true
  },
  {
    "source": "/only-in-wadi-al-natron",
    "destination": "/guide/wadi-al-natron",
    "permanent": true
  },
  {
    "source": "/how-to-reach-al-gouna",
    "destination": "/guide/al-gouna/how-to-reach-al-gouna",
    "permanent": true
  },
  {
    "source": "/zeytouna-beach",
    "destination": "/guide/al-gouna",
    "permanent": true
  },
  {
    "source": "/al-gouna-travel-guide/mangroovy-beach",
    "destination": "/guide/al-gouna",
    "permanent": true
  },
  {
    "source": "/traditional-food-in-al-gouna",
    "destination": "/guide/al-gouna/traditional-food-in-al-gouna",
    "permanent": true
  },
  {
    "source": "/only-in-al-gouna",
    "destination": "/guide/al-gouna/only-in-al-gouna",
    "permanent": true
  },
  {
    "source": "/al-gouna-festivals-and-celebrations",
    "destination": "/guide/al-gouna/al-gouna-festivals-and-celebrations",
    "permanent": true
  },
  {
    "source": "/getting-to-alexandria",
    "destination": "/guide/alexandria/getting-to-alexandria",
    "permanent": true
  },
  {
    "source": "/how-to-get-around-alexandria",
    "destination": "/guide/alexandria/how-to-get-around-alexandria",
    "permanent": true
  },
  {
    "source": "/only-here-in-alexandria",
    "destination": "/guide/alexandria/only-here-in-alexandria",
    "permanent": true
  },
  {
    "source": "/necropolis-of-anfushi",
    "destination": "/guide/alexandria",
    "permanent": true
  },
  {
    "source": "/the-pharos-lighthouse",
    "destination": "/guide/alexandria",
    "permanent": true
  },
  {
    "source": "/the-royal-palaces",
    "destination": "/guide/alexandria",
    "permanent": true
  },
  {
    "source": "/catacombs-of-kom-el-shuqafa",
    "destination": "/guide/alexandria",
    "permanent": true
  },
  {
    "source": "/pompeys-pillar",
    "destination": "/guide/alexandria",
    "permanent": true
  },
  {
    "source": "/the-roman-amphitheater",
    "destination": "/guide/alexandria",
    "permanent": true
  },
  {
    "source": "/qaitbey-fort",
    "destination": "/guide/alexandria",
    "permanent": true
  },
  {
    "source": "/how-to-reach-aswan",
    "destination": "/guide/aswan/how-to-reach-aswan",
    "permanent": true
  },
  {
    "source": "/traditional-food-in-aswan",
    "destination": "/guide/aswan/traditional-food-in-aswan",
    "permanent": true
  },
  {
    "source": "/tombs-of-the-nobles-in-aswan",
    "destination": "/guide/aswan/tombs-of-the-nobles-in-aswan",
    "permanent": true
  },
  {
    "source": "/aswan-festivals-and-celebrations",
    "destination": "/guide/aswan/aswan-festivals-and-celebrations",
    "permanent": true
  },
  {
    "source": "/the-botanical-garden",
    "destination": "/guide/aswan",
    "permanent": true
  },
  {
    "source": "/aswan-local-market",
    "destination": "/guide/aswan/aswan-local-market",
    "permanent": true
  },
  {
    "source": "/aswan-high-dam",
    "destination": "/guide/aswan/aswan-high-dam",
    "permanent": true
  },
  {
    "source": "/convent-of-the-holy-virgin-at-dorunka",
    "destination": "/guide/asyut",
    "permanent": true
  },
  {
    "source": "/what-to-eat-in-asyut",
    "destination": "/guide/asyut/what-to-eat-in-asyut",
    "permanent": true
  },
  {
    "source": "/only-here-in-asyut",
    "destination": "/guide/asyut/only-here-in-asyut",
    "permanent": true
  },
  {
    "source": "/only-here-in-bahariya-oasis",
    "destination": "/guide/bahariya-oasis/only-here-in-bahariya-oasis",
    "permanent": true
  },
  {
    "source": "/valley-of-the-golden-mummies",
    "destination": "/guide/bahariya-oasis",
    "permanent": true
  },
  {
    "source": "/el-hayz",
    "destination": "/guide/bahariya-oasis",
    "permanent": true
  },
  {
    "source": "/al-qasr-village",
    "destination": "/guide/bahariya-oasis",
    "permanent": true
  },
  {
    "source": "/bawiti",
    "destination": "/guide/bahariya-oasis",
    "permanent": true
  },
  {
    "source": "/the-crystal-mountain",
    "destination": "/guide/bahariya-oasis",
    "permanent": true
  },
  {
    "source": "/how-to-reach-beni-suef",
    "destination": "/guide/beni-suef/how-to-reach-beni-suef",
    "permanent": true
  },
  {
    "source": "/ehnasya-el-medina",
    "destination": "/guide/beni-suef",
    "permanent": true
  },
  {
    "source": "/dishasha",
    "destination": "/guide/beni-suef",
    "permanent": true
  },
  {
    "source": "/only-here-in-beni-suef",
    "destination": "/guide/beni-suef/only-here-in-beni-suef",
    "permanent": true
  },
  {
    "source": "/al-mezauwaqa",
    "destination": "/guide/dakhla-oasis",
    "permanent": true
  },
  {
    "source": "/weather-in-dakhla-oasis",
    "destination": "/guide/dakhla-oasis/weather-in-dakhla-oasis",
    "permanent": true
  },
  {
    "source": "/dakhla-oasis/deir-el-hagar",
    "destination": "/guide/dakhla-oasis",
    "permanent": true
  },
  {
    "source": "/egypt-travel-guide/dakhla-oasis/food-2",
    "destination": "/guide/dakhla-oasis",
    "permanent": true
  },
  {
    "source": "/only-here-in-dakhla-oasis",
    "destination": "/guide/dakhla-oasis/only-here-in-dakhla-oasis",
    "permanent": true
  },
  {
    "source": "/egypt-travel-guide/dakhla-oasis/where-to-stay",
    "destination": "/guide/dakhla-oasis",
    "permanent": true
  },
  {
    "source": "/what-to-do-in-edfu",
    "destination": "/guide/edfu/what-to-do-in-edfu",
    "permanent": true
  },
  {
    "source": "/popular-tours-in-edfu",
    "destination": "/guide/edfu",
    "permanent": true
  },
  {
    "source": "/edfu-food-and-drink",
    "destination": "/guide/edfu/edfu-food-and-drink",
    "permanent": true
  },
  {
    "source": "/the-hidden-valley-and-the-new-white-desert",
    "destination": "/guide/farafra-oasis",
    "permanent": true
  },
  {
    "source": "/white-desert-national-park",
    "destination": "/guide/farafra-oasis",
    "permanent": true
  },
  {
    "source": "/el-qaf",
    "destination": "/guide/farafra-oasis",
    "permanent": true
  },
  {
    "source": "/crystal-mountain-and-agabat",
    "destination": "/guide/farafra-oasis",
    "permanent": true
  },
  {
    "source": "/off-road-from-farafra-to-dakhla",
    "destination": "/guide/farafra-oasis",
    "permanent": true
  },
  {
    "source": "/palm-groves",
    "destination": "/guide/farafra-oasis",
    "permanent": true
  },
  {
    "source": "/ghard-abu-muharrik-and-the-sand-volcano",
    "destination": "/guide/farafra-oasis",
    "permanent": true
  },
  {
    "source": "/qasr-al-farafra",
    "destination": "/guide/farafra-oasis/qasr-al-farafra",
    "permanent": true
  },
  {
    "source": "/road-to-dakhla",
    "destination": "/guide/farafra-oasis",
    "permanent": true
  },
  {
    "source": "/the-white-desert",
    "destination": "/guide/farafra-oasis",
    "permanent": true
  },
  {
    "source": "/accommodations-in-farafra",
    "destination": "/guide/farafra-oasis/accommodations-in-farafra",
    "permanent": true
  },
  {
    "source": "/top-hotels-in-giza",
    "destination": "/guide/giza/top-hotels-in-giza",
    "permanent": true
  },
  {
    "source": "/navigating-giza",
    "destination": "/guide/giza/navigating-giza",
    "permanent": true
  },
  {
    "source": "/only-in-giza",
    "destination": "/guide/giza/only-in-giza",
    "permanent": true
  },
  {
    "source": "/top-tours-in-giza",
    "destination": "/guide/giza",
    "permanent": true
  },
  {
    "source": "/public-transport-in-hurghada",
    "destination": "/guide/hurghada/public-transport-in-hurghada",
    "permanent": true
  },
  {
    "source": "/where-to-sleep-in-hurghada",
    "destination": "/guide/hurghada/where-to-sleep-in-hurghada",
    "permanent": true
  },
  {
    "source": "/what-to-eat-in-hurghada",
    "destination": "/guide/hurghada/what-to-eat-in-hurghada",
    "permanent": true
  },
  {
    "source": "/hurghada-marina",
    "destination": "/guide/hurghada/hurghada-marina",
    "permanent": true
  },
  {
    "source": "/hurghada-aquarium",
    "destination": "/guide/hurghada/hurghada-aquarium",
    "permanent": true
  },
  {
    "source": "/giftun-islands",
    "destination": "/guide/hurghada",
    "permanent": true
  },
  {
    "source": "/straits-of-gubal",
    "destination": "/guide/hurghada",
    "permanent": true
  },
  {
    "source": "/abu-nuhas-shipwreck-sites",
    "destination": "/guide/hurghada",
    "permanent": true
  },
  {
    "source": "/accommodation-options-ismailia",
    "destination": "/guide/ismailia/accommodation-options-ismailia",
    "permanent": true
  },
  {
    "source": "/ismailia-flavors",
    "destination": "/guide/ismailia/ismailia-flavors",
    "permanent": true
  },
  {
    "source": "/only-here-in-ismailia",
    "destination": "/guide/ismailia/only-here-in-ismailia",
    "permanent": true
  },
  {
    "source": "/navigating-ismailia",
    "destination": "/guide/ismailia/navigating-ismailia",
    "permanent": true
  },
  {
    "source": "/top-tours-in-kharga-oasis",
    "destination": "/guide/kharga-oasis",
    "permanent": true
  },
  {
    "source": "/the-speos-of-horemheb",
    "destination": "/guide/kom-ombo",
    "permanent": true
  },
  {
    "source": "/gebel-el-silsila",
    "destination": "/guide/kom-ombo",
    "permanent": true
  },
  {
    "source": "/public-transport-in-kom-ombo",
    "destination": "/guide/kom-ombo/public-transport-in-kom-ombo",
    "permanent": true
  },
  {
    "source": "/explore-kom-ombo-activities",
    "destination": "/guide/kom-ombo",
    "permanent": true
  },
  {
    "source": "/where-to-sleep-in-kom-ombo",
    "destination": "/guide/kom-ombo/where-to-sleep-in-kom-ombo",
    "permanent": true
  },
  {
    "source": "/what-to-eat-in-kom-ombo",
    "destination": "/guide/kom-ombo/what-to-eat-in-kom-ombo",
    "permanent": true
  },
  {
    "source": "/kom-ombo-unforgettable-moments",
    "destination": "/guide/kom-ombo/kom-ombo-unforgettable-moments",
    "permanent": true
  },
  {
    "source": "/annual-events-in-kom-ombo",
    "destination": "/guide/kom-ombo/annual-events-in-kom-ombo",
    "permanent": true
  },
  {
    "source": "/top-restaurants-in-luxor",
    "destination": "/guide/luxor/top-restaurants-in-luxor",
    "permanent": true
  },
  {
    "source": "/luxor-off-the-beaten-path",
    "destination": "/guide/luxor/luxor-off-the-beaten-path",
    "permanent": true
  },
  {
    "source": "/cultural-events-in-luxor",
    "destination": "/guide/luxor/cultural-events-in-luxor",
    "permanent": true
  },
  {
    "source": "/the-valley-of-the-queens",
    "destination": "/guide/luxor",
    "permanent": true
  },
  {
    "source": "/the-valley-of-the-kings",
    "destination": "/guide/luxor",
    "permanent": true
  },
  {
    "source": "/deir-el-madina",
    "destination": "/guide/luxor",
    "permanent": true
  },
  {
    "source": "/luxor-ancient-past",
    "destination": "/guide/luxor/luxor-ancient-past",
    "permanent": true
  },
  {
    "source": "/luxor-climate",
    "destination": "/guide/luxor/luxor-climate",
    "permanent": true
  },
  {
    "source": "/travel-to-luxor",
    "destination": "/guide/luxor/travel-to-luxor",
    "permanent": true
  },
  {
    "source": "/what-to-do-in-luxor",
    "destination": "/guide/luxor/what-to-do-in-luxor",
    "permanent": true
  },
  {
    "source": "/when-to-go-marsa-alam",
    "destination": "/guide/marsa-alam/when-to-go-marsa-alam",
    "permanent": true
  },
  {
    "source": "/the-town-of-marsa-alam",
    "destination": "/guide/marsa-alam/the-town-of-marsa-alam",
    "permanent": true
  },
  {
    "source": "/hamata-islands-qulaan-archipelago",
    "destination": "/guide/marsa-alam",
    "permanent": true
  },
  {
    "source": "/the-camel-market-at-shalateen",
    "destination": "/guide/marsa-alam",
    "permanent": true
  },
  {
    "source": "/sharm-el-luli",
    "destination": "/guide/marsa-alam",
    "permanent": true
  },
  {
    "source": "/sataya-reef",
    "destination": "/guide/marsa-alam",
    "permanent": true
  },
  {
    "source": "/port-ghalib-marina",
    "destination": "/guide/marsa-alam",
    "permanent": true
  },
  {
    "source": "/abu-dabbab-beach",
    "destination": "/guide/marsa-alam",
    "permanent": true
  },
  {
    "source": "/wadi-el-gamal-national-park",
    "destination": "/guide/marsa-alam/wadi-el-gamal-national-park",
    "permanent": true
  },
  {
    "source": "/marsa-alam-flavors",
    "destination": "/guide/marsa-alam/marsa-alam-flavors",
    "permanent": true
  },
  {
    "source": "/only-in-marsa-alam",
    "destination": "/guide/marsa-alam/only-in-marsa-alam",
    "permanent": true
  },
  {
    "source": "/places-to-go-in-marsa-matruh",
    "destination": "/guide/marsa-matruh/places-to-go-in-marsa-matruh",
    "permanent": true
  },
  {
    "source": "/marsa-matruh-events",
    "destination": "/guide/marsa-matruh/marsa-matruh-events",
    "permanent": true
  },
  {
    "source": "/uncovering-nuweiba-heritage",
    "destination": "/guide/nuweiba",
    "permanent": true
  },
  {
    "source": "/nuweiba-hotel-guide",
    "destination": "/guide/nuweiba/nuweiba-hotel-guide",
    "permanent": true
  },
  {
    "source": "/tours-in-nuweiba",
    "destination": "/guide/nuweiba",
    "permanent": true
  },
  {
    "source": "/only-in-nuweiba",
    "destination": "/guide/nuweiba/only-in-nuweiba",
    "permanent": true
  },
  {
    "source": "/cultural-events-in-nuweiba",
    "destination": "/guide/nuweiba",
    "permanent": true
  },
  {
    "source": "/the-tarabin-beach",
    "destination": "/guide/nuweiba",
    "permanent": true
  },
  {
    "source": "/lodging-in-port-said",
    "destination": "/guide/port-said/lodging-in-port-said",
    "permanent": true
  },
  {
    "source": "/planning-your-trip-to-port-said",
    "destination": "/guide/port-said",
    "permanent": true
  },
  {
    "source": "/suez-canal-house",
    "destination": "/guide/port-said",
    "permanent": true
  },
  {
    "source": "/waterfront-quarter-port-said",
    "destination": "/guide/port-said/waterfront-quarter-port-said",
    "permanent": true
  },
  {
    "source": "/tours-to-enjoy-in-port-said",
    "destination": "/guide/port-said",
    "permanent": true
  },
  {
    "source": "/port-said-food-and-drink",
    "destination": "/guide/port-said/port-said-food-and-drink",
    "permanent": true
  },
  {
    "source": "/navigating-qena",
    "destination": "/guide/qena/navigating-qena",
    "permanent": true
  },
  {
    "source": "/only-in-qena",
    "destination": "/guide/qena/only-in-qena",
    "permanent": true
  },
  {
    "source": "/upcoming-events-in-qena",
    "destination": "/guide/qena/upcoming-events-in-qena",
    "permanent": true
  },
  {
    "source": "/sacred-lake",
    "destination": "/guide/qena",
    "permanent": true
  },
  {
    "source": "/hathor-and-bes",
    "destination": "/guide/qena",
    "permanent": true
  },
  {
    "source": "/the-roof-chapels-of-hathor",
    "destination": "/guide/qena",
    "permanent": true
  },
  {
    "source": "/hypostyle-ceiling",
    "destination": "/guide/qena",
    "permanent": true
  },
  {
    "source": "/roman-mammisi",
    "destination": "/guide/qena",
    "permanent": true
  },
  {
    "source": "/ras-sudr-ancient-past",
    "destination": "/guide/ras-sudr/ras-sudr-ancient-past",
    "permanent": true
  },
  {
    "source": "/ras-sudr-climate",
    "destination": "/guide/ras-sudr/ras-sudr-climate",
    "permanent": true
  },
  {
    "source": "/travel-to-ras-sudr",
    "destination": "/guide/ras-sudr/travel-to-ras-sudr",
    "permanent": true
  },
  {
    "source": "/ras-sudr-local-transport-guide",
    "destination": "/guide/ras-sudr/ras-sudr-local-transport-guide",
    "permanent": true
  },
  {
    "source": "/places-to-visit-in-ras-sudr",
    "destination": "/guide/ras-sudr/places-to-visit-in-ras-sudr",
    "permanent": true
  },
  {
    "source": "/explore-ras-sudr-tours",
    "destination": "/guide/ras-sudr/explore-ras-sudr-tours",
    "permanent": true
  },
  {
    "source": "/top-restaurants-in-ras-sudr",
    "destination": "/guide/ras-sudr/top-restaurants-in-ras-sudr",
    "permanent": true
  },
  {
    "source": "/only-in-ras-sudr",
    "destination": "/guide/ras-sudr/only-in-ras-sudr",
    "permanent": true
  },
  {
    "source": "/places-to-stay-in-ras-sudr",
    "destination": "/guide/ras-sudr/places-to-stay-in-ras-sudr",
    "permanent": true
  },
  {
    "source": "/outstanding-islamic-and-ottoman-places-in-rosetta",
    "destination": "/guide/rosetta-rasheed",
    "permanent": true
  },
  {
    "source": "/only-in-rosetta",
    "destination": "/guide/rosetta-rasheed/only-in-rosetta",
    "permanent": true
  },
  {
    "source": "/taste-of-rosetta",
    "destination": "/guide/rosetta-rasheed/taste-of-rosetta",
    "permanent": true
  },
  {
    "source": "/places-to-go-in-safaga",
    "destination": "/guide/safaga/places-to-go-in-safaga",
    "permanent": true
  },
  {
    "source": "/only-in-safaga",
    "destination": "/guide/safaga/only-in-safaga",
    "permanent": true
  },
  {
    "source": "/annual-events-in-safaga",
    "destination": "/guide/safaga",
    "permanent": true
  },
  {
    "source": "/only-in-saint-catherine",
    "destination": "/guide/saint-catherine/only-in-saint-catherine",
    "permanent": true
  },
  {
    "source": "/saint-catherine-mountain",
    "destination": "/guide/saint-catherine/saint-catherine-mountain",
    "permanent": true
  },
  {
    "source": "/moses-mountain",
    "destination": "/guide/saint-catherine",
    "permanent": true
  },
  {
    "source": "/accommodations-in-sharm-el-sheikh",
    "destination": "/guide/sharm-el-sheikh/accommodations-in-sharm-el-sheikh",
    "permanent": true
  },
  {
    "source": "/only-in-sharm-el-sheikh",
    "destination": "/guide/sharm-el-sheikh/only-in-sharm-el-sheikh",
    "permanent": true
  },
  {
    "source": "/top-tours-in-sharm-el-sheikh",
    "destination": "/guide/sharm-el-sheikh",
    "permanent": true
  },
  {
    "source": "/nabq-national-park",
    "destination": "/guide/sharm-el-sheikh/nabq-national-park",
    "permanent": true
  },
  {
    "source": "/ras-mohamed-national-park",
    "destination": "/guide/sharm-el-sheikh",
    "permanent": true
  },
  {
    "source": "/naama-bay-sharm-el-sheikh-guide",
    "destination": "/guide/sharm-el-sheikh/naama-bay-sharm-el-sheikh-guide",
    "permanent": true
  },
  {
    "source": "/uncovering-siwa-heritage",
    "destination": "/guide/siwa-oasis",
    "permanent": true
  },
  {
    "source": "/siwa-hotel-guide",
    "destination": "/guide/siwa-oasis/siwa-hotel-guide",
    "permanent": true
  },
  {
    "source": "/reaching-siwa-egypt",
    "destination": "/guide/siwa-oasis",
    "permanent": true
  },
  {
    "source": "/tours-in-siwa",
    "destination": "/guide/siwa-oasis",
    "permanent": true
  },
  {
    "source": "/cleopatra-pool",
    "destination": "/guide/siwa-oasis",
    "permanent": true
  },
  {
    "source": "/dakrour-mountain",
    "destination": "/guide/siwa-oasis",
    "permanent": true
  },
  {
    "source": "/mountain-of-the-dead",
    "destination": "/guide/siwa-oasis",
    "permanent": true
  },
  {
    "source": "/salt-lakes",
    "destination": "/guide/siwa-oasis",
    "permanent": true
  },
  {
    "source": "/uncovering-sohag-heritage",
    "destination": "/guide/sohag",
    "permanent": true
  },
  {
    "source": "/sohag-hotel-guide",
    "destination": "/guide/sohag/sohag-hotel-guide",
    "permanent": true
  },
  {
    "source": "/reaching-sohag-egypt",
    "destination": "/guide/sohag",
    "permanent": true
  },
  {
    "source": "/story-of-suez",
    "destination": "/guide/suez/story-of-suez",
    "permanent": true
  },
  {
    "source": "/suez-temperature-trends",
    "destination": "/guide/suez/suez-temperature-trends",
    "permanent": true
  },
  {
    "source": "/ways-to-get-to-suez",
    "destination": "/guide/suez/ways-to-get-to-suez",
    "permanent": true
  },
  {
    "source": "/cultural-tours-in-suez",
    "destination": "/guide/suez",
    "permanent": true
  },
  {
    "source": "/eating-out-in-suez",
    "destination": "/guide/suez/eating-out-in-suez",
    "permanent": true
  },
  {
    "source": "/story-of-taba",
    "destination": "/guide/taba/story-of-taba",
    "permanent": true
  },
  {
    "source": "/taba-temperature-trends",
    "destination": "/guide/taba/taba-temperature-trends",
    "permanent": true
  },
  {
    "source": "/ways-to-get-to-taba",
    "destination": "/guide/taba/ways-to-get-to-taba",
    "permanent": true
  },
  {
    "source": "/best-places-to-stay-taba",
    "destination": "/guide/taba/best-places-to-stay-taba",
    "permanent": true
  },
  {
    "source": "/taba-heights",
    "destination": "/guide/taba/taba-heights",
    "permanent": true
  },
  {
    "source": "/only-in-taba",
    "destination": "/guide/taba/only-in-taba",
    "permanent": true
  },
  {
    "source": "/eating-out-in-taba",
    "destination": "/guide/taba/eating-out-in-taba",
    "permanent": true
  },
  {
    "source": "/cultural-tours-in-taba",
    "destination": "/guide/taba",
    "permanent": true
  },
  {
    "source": "/how-to-go-in-al-wadi-al-gadid",
    "destination": "/guide/al-wadi-al-gadid/how-to-go-in-al-wadi-al-gadid",
    "permanent": true
  },
  {
    "source": "/top-tours-in-al-wadi-al-gadid",
    "destination": "/guide/al-wadi-al-gadid",
    "permanent": true
  },
  {
    "source": "/planning-your-trip-to-dahab",
    "destination": "/guide/dahab",
    "permanent": true
  },
  {
    "source": "/experiences-in-dahab",
    "destination": "/guide/dahab/experiences-in-dahab",
    "permanent": true
  },
  {
    "source": "/abu-galum-protectorate",
    "destination": "/guide/dahab",
    "permanent": true
  },
  {
    "source": "/private-tours-in-dahab",
    "destination": "/guide/dahab",
    "permanent": true
  }
];
