/* eslint-disable */
// AUTO-GENERATED by scripts/wp-import/redirect-map-regenerate.ts.
// Do not edit by hand. Run `npm run redirect-map:regenerate` to refresh.
//
// Source of truth: migration/redirect-map.csv.
// Imported by next.config.ts to populate `async redirects()`.

export interface RedirectRule {
  source: string;
  destination: string;
  permanent: boolean;
}

export const redirects: RedirectRule[] = [
  {
    "source": "/fi/kuinka-pukeutua-vieraillessa-egyptissa",
    "destination": "/",
    "permanent": true
  },
  {
    "source": "/fi/liikkuminen-egyptissa",
    "destination": "/",
    "permanent": true
  },
  {
    "source": "/fi/egyptin-hieroglyfien-ymmartaminen",
    "destination": "/",
    "permanent": true
  },
  {
    "source": "/nile-cruise-holidays",
    "destination": "/nile-cruises/nile-cruise-holidays",
    "permanent": true
  },
  {
    "source": "/es/vacaciones-en-un-crucero-por-el-nilo",
    "destination": "/es/nile-cruises/vacaciones-en-un-crucero-por-el-nilo",
    "permanent": true
  },
  {
    "source": "/ja/ナイルクルーズの休日",
    "destination": "/ja/nile-cruises/ナイルクルーズの休日",
    "permanent": true
  },
  {
    "source": "/fi/boutique-niilin-risteilyt",
    "destination": "/",
    "permanent": true
  },
  {
    "source": "/fi/kuinka-valita-sim-kortti-egyptin-matkalle",
    "destination": "/",
    "permanent": true
  },
  {
    "source": "/fi/suuren-gizan-pyramidin-sisaan",
    "destination": "/",
    "permanent": true
  },
  {
    "source": "/m-s-amwaj-livingstone-nile-cruise",
    "destination": "/nile-cruises/m-s-amwaj-livingstone-nile-cruise",
    "permanent": true
  },
  {
    "source": "/es/m-s-amwaj-livingstone",
    "destination": "/es/nile-cruises/m-s-amwaj-livingstone",
    "permanent": true
  },
  {
    "source": "/ja/m-s-アムワジ・リビングストン",
    "destination": "/ja/nile-cruises/m-s-アムワジ・リビングストン",
    "permanent": true
  },
  {
    "source": "/es/m-s-al-kahila-crucero-por-el-nilo",
    "destination": "/es/nile-cruises/m-s-al-kahila-crucero-por-el-nilo",
    "permanent": true
  },
  {
    "source": "/ja/m-s-アル・ジャミラ・ナイル・クルーズ（m-s-al-jamila-nile-cruise）",
    "destination": "/ja/nile-cruises/m-s-アル・ジャミラ・ナイル・クルーズ（m-s-al-jamila-nile-cruise）",
    "permanent": true
  },
  {
    "source": "/m-s-nubian-sea",
    "destination": "/nile-cruises/m-s-nubian-sea",
    "permanent": true
  },
  {
    "source": "/ja/m-s-ヌビアン・シー（m-s-nubian-sea）",
    "destination": "/ja/nile-cruises/m-s-ヌビアン・シー（m-s-nubian-sea）",
    "permanent": true
  },
  {
    "source": "/agatha-dahabiya",
    "destination": "/nile-cruises/agatha-dahabiya",
    "permanent": true
  },
  {
    "source": "/es/agatha-dahabiya",
    "destination": "/es/nile-cruises/agatha-dahabiya",
    "permanent": true
  },
  {
    "source": "/ja/アガサ・ダハビヤ（agatha-dahabiya）",
    "destination": "/ja/nile-cruises/アガサ・ダハビヤ（agatha-dahabiya）",
    "permanent": true
  },
  {
    "source": "/ms-esplanade-nile-cruise",
    "destination": "/nile-cruises/ms-esplanade-nile-cruise",
    "permanent": true
  },
  {
    "source": "/es/ms-esplanade-nile-cruise",
    "destination": "/es/nile-cruises/ms-esplanade-nile-cruise",
    "permanent": true
  },
  {
    "source": "/ja/m-s-エスプラナード・ナイル・クルーズ（m-s-esplanade-nile-cruise）",
    "destination": "/ja/nile-cruises/m-s-エスプラナード・ナイル・クルーズ（m-s-esplanade-nile-cruise）",
    "permanent": true
  },
  {
    "source": "/m-s-al-kahila-nile-cruise",
    "destination": "/nile-cruises/m-s-al-kahila-nile-cruise",
    "permanent": true
  },
  {
    "source": "/ja/m-s-ソネスタ・ムーン・ゴッデス",
    "destination": "/ja/nile-cruises/m-s-ソネスタ・ムーン・ゴッデス",
    "permanent": true
  },
  {
    "source": "/es/m-s-al-jamila-crucero-por-el-nilo",
    "destination": "/es/nile-cruises/m-s-al-jamila-crucero-por-el-nilo",
    "permanent": true
  },
  {
    "source": "/ja/m-s-メイフェア・ナイル・クルーズ（m-s-mayfair-nile-cruise）",
    "destination": "/ja/nile-cruises/m-s-メイフェア・ナイル・クルーズ（m-s-mayfair-nile-cruise）",
    "permanent": true
  },
  {
    "source": "/ja/オベロイ・ザフラ・ナイル・クルーズ（oberoi-zahra-nile-cruise）",
    "destination": "/ja/nile-cruises/オベロイ・ザフラ・ナイル・クルーズ（oberoi-zahra-nile-cruise）",
    "permanent": true
  },
  {
    "source": "/meroe-dahabiya",
    "destination": "/nile-cruises/meroe-dahabiya",
    "permanent": true
  },
  {
    "source": "/es/meroe-dahabiya",
    "destination": "/es/nile-cruises/meroe-dahabiya",
    "permanent": true
  },
  {
    "source": "/ja/メロエ・ダハビヤ",
    "destination": "/ja/nile-cruises/メロエ・ダハビヤ",
    "permanent": true
  },
  {
    "source": "/m-s-moon-goddess-nile-cruise",
    "destination": "/nile-cruises/m-s-moon-goddess-nile-cruise",
    "permanent": true
  },
  {
    "source": "/es/m-s-sonesta-diosa-de-la-luna",
    "destination": "/es/nile-cruises/m-s-sonesta-diosa-de-la-luna",
    "permanent": true
  },
  {
    "source": "/the-nile-goddess-cruise",
    "destination": "/nile-cruises/the-nile-goddess-cruise",
    "permanent": true
  },
  {
    "source": "/es/el-crucero-de-la-diosa-del-nilo",
    "destination": "/es/nile-cruises/el-crucero-de-la-diosa-del-nilo",
    "permanent": true
  },
  {
    "source": "/ja/ナイル・ゴッデス・クルーズ",
    "destination": "/ja/nile-cruises/ナイル・ゴッデス・クルーズ",
    "permanent": true
  },
  {
    "source": "/roman-dahabiya",
    "destination": "/nile-cruises/roman-dahabiya",
    "permanent": true
  },
  {
    "source": "/es/roman-dahabiya",
    "destination": "/es/nile-cruises/roman-dahabiya",
    "permanent": true
  },
  {
    "source": "/ja/ローマン・ダハビヤ（roman-dahabiya）",
    "destination": "/ja/nile-cruises/ローマン・ダハビヤ（roman-dahabiya）",
    "permanent": true
  },
  {
    "source": "/movenpick-sb-feddya-dahabiya",
    "destination": "/nile-cruises/movenpick-sb-feddya-dahabiya",
    "permanent": true
  },
  {
    "source": "/es/movenpick-sb-feddya-dahabiya",
    "destination": "/es/nile-cruises/movenpick-sb-feddya-dahabiya",
    "permanent": true
  },
  {
    "source": "/ja/sb-フェディヤ・ダハビヤ（sb-feddya-dahabiya）",
    "destination": "/ja/nile-cruises/sb-フェディヤ・ダハビヤ（sb-feddya-dahabiya）",
    "permanent": true
  },
  {
    "source": "/nour-el-nil-assouan-dahabiya",
    "destination": "/nile-cruises/nour-el-nil-assouan-dahabiya",
    "permanent": true
  },
  {
    "source": "/es/nour-el-nil-assouan-dahabiya",
    "destination": "/es/nile-cruises/nour-el-nil-assouan-dahabiya",
    "permanent": true
  },
  {
    "source": "/ja/ヌール・エル・ニール・アスワン・ダハビーヤ",
    "destination": "/ja/nile-cruises/ヌール・エル・ニール・アスワン・ダハビーヤ",
    "permanent": true
  },
  {
    "source": "/oberoi-zahra-nile-cruise",
    "destination": "/nile-cruises/oberoi-zahra-nile-cruise",
    "permanent": true
  },
  {
    "source": "/es/oberoi-zahra-nile-cruise",
    "destination": "/es/nile-cruises/oberoi-zahra-nile-cruise",
    "permanent": true
  },
  {
    "source": "/ja/m-s-アル・カヒラ・ナイル・クルーズ（m-s-al-kahila-nile-cruise）",
    "destination": "/ja/nile-cruises/m-s-アル・カヒラ・ナイル・クルーズ（m-s-al-kahila-nile-cruise）",
    "permanent": true
  },
  {
    "source": "/ja/m-s-ソネスタ・スター・ゴッデス（m-s-sonesta-star-goddess）",
    "destination": "/ja/nile-cruises/m-s-ソネスタ・スター・ゴッデス（m-s-sonesta-star-goddess）",
    "permanent": true
  },
  {
    "source": "/es/m-s-omar-el-khayam",
    "destination": "/es/nile-cruises/m-s-omar-el-khayam",
    "permanent": true
  },
  {
    "source": "/fi/sphinxes-and-obelisks-how-egypts-silent-giants-still-speak-today",
    "destination": "/",
    "permanent": true
  },
  {
    "source": "/m-s-sonesta-st-george-nile-cruise",
    "destination": "/nile-cruises/m-s-sonesta-st-george-nile-cruise",
    "permanent": true
  },
  {
    "source": "/es/m-s-sonesta-st",
    "destination": "/es/nile-cruises/m-s-sonesta-st",
    "permanent": true
  },
  {
    "source": "/m-s-steigenberger-omar-el-khayam",
    "destination": "/nile-cruises/m-s-steigenberger-omar-el-khayam",
    "permanent": true
  },
  {
    "source": "/ja/m-s-オマール・エル・ハイヤム（m-s-omar-el-khayam）",
    "destination": "/ja/nile-cruises/m-s-オマール・エル・ハイヤム（m-s-omar-el-khayam）",
    "permanent": true
  },
  {
    "source": "/nour-el-nil-meroe-dahabiya",
    "destination": "/nile-cruises/nour-el-nil-meroe-dahabiya",
    "permanent": true
  },
  {
    "source": "/es/nour-el-nil-meroe-dahabiya",
    "destination": "/es/nile-cruises/nour-el-nil-meroe-dahabiya",
    "permanent": true
  },
  {
    "source": "/fi/taydellinen-opas-kairon-nmeciin-egyptilaisen-sivilisaation-kansallismuseo",
    "destination": "/",
    "permanent": true
  },
  {
    "source": "/fi/paikalliset-sairaalat-egyptissa",
    "destination": "/",
    "permanent": true
  },
  {
    "source": "/fi/missa-tutankhamun-on-nyt",
    "destination": "/",
    "permanent": true
  },
  {
    "source": "/agatha-dahabiya-journey-along-the-nile",
    "destination": "/nile-cruises/agatha-dahabiya-journey-along-the-nile",
    "permanent": true
  },
  {
    "source": "/es/el-agatha-dahabiya-descubriendo-el-rio-eterno-de-egipto",
    "destination": "/es/nile-cruises/el-agatha-dahabiya-descubriendo-el-rio-eterno-de-egipto",
    "permanent": true
  },
  {
    "source": "/ja/アガサ・ダハビーヤ：ナイル川をたどる旅",
    "destination": "/ja/nile-cruises/アガサ・ダハビーヤ：ナイル川をたどる旅",
    "permanent": true
  },
  {
    "source": "/adelaide-dahabiya-nile-cruise",
    "destination": "/nile-cruises/adelaide-dahabiya-nile-cruise",
    "permanent": true
  },
  {
    "source": "/es/descubriendo-el-nilo-un-viaje-a-bordo-del-adelaide-dahabiya",
    "destination": "/es/nile-cruises/descubriendo-el-nilo-un-viaje-a-bordo-del-adelaide-dahabiya",
    "permanent": true
  },
  {
    "source": "/ja/ナイル探求の旅：アデライード・ダハビーヤ号で",
    "destination": "/ja/nile-cruises/ナイル探求の旅：アデライード・ダハビーヤ号で",
    "permanent": true
  },
  {
    "source": "/adelaide-dahabiya",
    "destination": "/nile-cruises/adelaide-dahabiya",
    "permanent": true
  },
  {
    "source": "/es/adelaide-dahabiya",
    "destination": "/es/nile-cruises/adelaide-dahabiya",
    "permanent": true
  },
  {
    "source": "/ja/アデライド・ダハビヤ（adelaide-dahabiya）",
    "destination": "/ja/nile-cruises/アデライド・ダハビヤ（adelaide-dahabiya）",
    "permanent": true
  },
  {
    "source": "/authentic-dahabiya-nile-cruise",
    "destination": "/nile-cruises/authentic-dahabiya-nile-cruise",
    "permanent": true
  },
  {
    "source": "/es/crucero-dahabiya-por-el-nilo",
    "destination": "/es/nile-cruises/crucero-dahabiya-por-el-nilo",
    "permanent": true
  },
  {
    "source": "/ja/ダハビーヤ・ナイルクルーズ",
    "destination": "/ja/nile-cruises/ダハビーヤ・ナイルクルーズ",
    "permanent": true
  },
  {
    "source": "/nour-el-nil-malouka-dahabiya",
    "destination": "/nile-cruises/nour-el-nil-malouka-dahabiya",
    "permanent": true
  },
  {
    "source": "/es/nour-el-nil-malouka-dahabiya",
    "destination": "/es/nile-cruises/nour-el-nil-malouka-dahabiya",
    "permanent": true
  },
  {
    "source": "/el-nil-dahabiya",
    "destination": "/nile-cruises/el-nil-dahabiya",
    "permanent": true
  },
  {
    "source": "/es/el-nil-dahabiya",
    "destination": "/es/nile-cruises/el-nil-dahabiya",
    "permanent": true
  },
  {
    "source": "/ja/エル・ニル・ダハビヤ",
    "destination": "/ja/nile-cruises/エル・ニル・ダハビヤ",
    "permanent": true
  },
  {
    "source": "/m-s-historia-nile-cruise",
    "destination": "/nile-cruises/m-s-historia-nile-cruise",
    "permanent": true
  },
  {
    "source": "/es/crucero-por-el-nilo-m-s-historia",
    "destination": "/es/nile-cruises/crucero-por-el-nilo-m-s-historia",
    "permanent": true
  },
  {
    "source": "/m-s-mayfair",
    "destination": "/nile-cruises/m-s-mayfair",
    "permanent": true
  },
  {
    "source": "/es/m-s-mayfair-crucero-por-el-nilo",
    "destination": "/es/nile-cruises/m-s-mayfair-crucero-por-el-nilo",
    "permanent": true
  },
  {
    "source": "/m-s-mayflower-nile-cruise",
    "destination": "/nile-cruises/m-s-mayflower-nile-cruise",
    "permanent": true
  },
  {
    "source": "/es/m-s-mayflower-nile-cruise",
    "destination": "/es/nile-cruises/m-s-mayflower-nile-cruise",
    "permanent": true
  },
  {
    "source": "/ja/m-sメイフラワー・ナイルクルーズ",
    "destination": "/ja/nile-cruises/m-sメイフラワー・ナイルクルーズ",
    "permanent": true
  },
  {
    "source": "/m-s-sonesta-star-goddess-nile-cruise",
    "destination": "/nile-cruises/m-s-sonesta-star-goddess-nile-cruise",
    "permanent": true
  },
  {
    "source": "/es/m-s-sonesta-star-goddess",
    "destination": "/es/nile-cruises/m-s-sonesta-star-goddess",
    "permanent": true
  },
  {
    "source": "/m-s-alexander-the-great-nile-cruise",
    "destination": "/nile-cruises/m-s-alexander-the-great-nile-cruise",
    "permanent": true
  },
  {
    "source": "/es/y-s-alejandro-magno",
    "destination": "/es/nile-cruises/y-s-alejandro-magno",
    "permanent": true
  },
  {
    "source": "/ja/y-s-アレクサンダー・ザ・グレート（y-s-alexander-the-great）",
    "destination": "/ja/nile-cruises/y-s-アレクサンダー・ザ・グレート（y-s-alexander-the-great）",
    "permanent": true
  },
  {
    "source": "/m-s-steigenberger-legacy-nile-cruise",
    "destination": "/nile-cruises/m-s-steigenberger-legacy-nile-cruise",
    "permanent": true
  },
  {
    "source": "/es/m-s-steigenberger-legacy-nile-cruise",
    "destination": "/es/nile-cruises/m-s-steigenberger-legacy-nile-cruise",
    "permanent": true
  },
  {
    "source": "/ja/m-s-シュタイゲンベルガー・レガシー（m-s-steigenberger-legacy）",
    "destination": "/ja/nile-cruises/m-s-シュタイゲンベルガー・レガシー（m-s-steigenberger-legacy）",
    "permanent": true
  },
  {
    "source": "/movenpick-ms-sun-ray-nile-cruise",
    "destination": "/nile-cruises/movenpick-ms-sun-ray-nile-cruise",
    "permanent": true
  },
  {
    "source": "/es/movenpick-m-s-sun-ray",
    "destination": "/es/nile-cruises/movenpick-m-s-sun-ray",
    "permanent": true
  },
  {
    "source": "/ja/モーヴェンピック-m-s-サン・レイ（movenpick-m-s-sun-ray）",
    "destination": "/ja/nile-cruises/モーヴェンピック-m-s-サン・レイ（movenpick-m-s-sun-ray）",
    "permanent": true
  },
  {
    "source": "/movenpick-ms-royal-lotus-nile-cruise",
    "destination": "/nile-cruises/movenpick-ms-royal-lotus-nile-cruise",
    "permanent": true
  },
  {
    "source": "/es/movenpick-ms-royal-lotus-nile-cruise",
    "destination": "/es/nile-cruises/movenpick-ms-royal-lotus-nile-cruise",
    "permanent": true
  },
  {
    "source": "/ja/モーヴェンピック-m-s-ロイヤル・ロータス（movenpick-m-s-royal-lotus",
    "destination": "/ja/nile-cruises/モーヴェンピック-m-s-ロイヤル・ロータス（movenpick-m-s-royal-lotus",
    "permanent": true
  },
  {
    "source": "/movenpick-ms-darakum-nile-cruise",
    "destination": "/nile-cruises/movenpick-ms-darakum-nile-cruise",
    "permanent": true
  },
  {
    "source": "/es/movenpick-ms-darakum-nile-cruise",
    "destination": "/es/nile-cruises/movenpick-ms-darakum-nile-cruise",
    "permanent": true
  },
  {
    "source": "/ja/モーヴェンピック-m-s-ダラクム（movenpick-m-s-darakum）",
    "destination": "/ja/nile-cruises/モーヴェンピック-m-s-ダラクム（movenpick-m-s-darakum）",
    "permanent": true
  },
  {
    "source": "/movenpick-ms-hamees-nile-cruise",
    "destination": "/nile-cruises/movenpick-ms-hamees-nile-cruise",
    "permanent": true
  },
  {
    "source": "/es/movenpick-ms-hamees-nile-cruise",
    "destination": "/es/nile-cruises/movenpick-ms-hamees-nile-cruise",
    "permanent": true
  },
  {
    "source": "/ja/モーヴェンピック-m-s-ハミーズ（movenpick-m-s-hamees）",
    "destination": "/ja/nile-cruises/モーヴェンピック-m-s-ハミーズ（movenpick-m-s-hamees）",
    "permanent": true
  },
  {
    "source": "/m-s-al-jamila-nile-cruise",
    "destination": "/nile-cruises/m-s-al-jamila-nile-cruise",
    "permanent": true
  },
  {
    "source": "/m-s-steigenberger-minerva-nile-cruise",
    "destination": "/nile-cruises/m-s-steigenberger-minerva-nile-cruise",
    "permanent": true
  },
  {
    "source": "/es/crucero-por-el-nilo-m-s-minerva",
    "destination": "/es/nile-cruises/crucero-por-el-nilo-m-s-minerva",
    "permanent": true
  },
  {
    "source": "/ja/m-s-ミネルヴァ・ナイル・クルーズ",
    "destination": "/ja/nile-cruises/m-s-ミネルヴァ・ナイル・クルーズ",
    "permanent": true
  },
  {
    "source": "/movenpick-prince-abbas-cruise",
    "destination": "/nile-cruises/movenpick-prince-abbas-cruise",
    "permanent": true
  },
  {
    "source": "/es/movenpick-prince-abbas-cruise",
    "destination": "/es/nile-cruises/movenpick-prince-abbas-cruise",
    "permanent": true
  },
  {
    "source": "/ja/モーヴェンピック・プリンス・アッバス",
    "destination": "/ja/nile-cruises/モーヴェンピック・プリンス・アッバス",
    "permanent": true
  },
  {
    "source": "/kasr-ibrim-cruise-ship",
    "destination": "/nile-cruises/kasr-ibrim-cruise-ship",
    "permanent": true
  },
  {
    "source": "/es/crucero-kasr-ibrim",
    "destination": "/es/nile-cruises/crucero-kasr-ibrim",
    "permanent": true
  },
  {
    "source": "/ja/カスル・イブリム・クルーズ・シップ",
    "destination": "/ja/nile-cruises/カスル・イブリム・クルーズ・シップ",
    "permanent": true
  },
  {
    "source": "/malouka-dahabiya",
    "destination": "/nile-cruises/malouka-dahabiya",
    "permanent": true
  },
  {
    "source": "/es/malouka-dahabiya",
    "destination": "/es/nile-cruises/malouka-dahabiya",
    "permanent": true
  },
  {
    "source": "/ja/マルーカ・ダハビヤ（malouka-dahabiya）",
    "destination": "/ja/nile-cruises/マルーカ・ダハビヤ（malouka-dahabiya）",
    "permanent": true
  },
  {
    "source": "/sonesta-amirat-dahabiya",
    "destination": "/nile-cruises/sonesta-amirat-dahabiya",
    "permanent": true
  },
  {
    "source": "/es/sonesta-amirat-dahabiya",
    "destination": "/es/nile-cruises/sonesta-amirat-dahabiya",
    "permanent": true
  },
  {
    "source": "/ja/amirat-dahabiya（アミラート",
    "destination": "/ja/nile-cruises/amirat-dahabiya（アミラート",
    "permanent": true
  },
  {
    "source": "/swiss-inn-radamis-ii-nile-cruise",
    "destination": "/nile-cruises/swiss-inn-radamis-ii-nile-cruise",
    "permanent": true
  },
  {
    "source": "/es/posada-suiza-radamis-ii",
    "destination": "/es/nile-cruises/posada-suiza-radamis-ii",
    "permanent": true
  },
  {
    "source": "/ja/スイス・イン・ラダミスii号",
    "destination": "/ja/nile-cruises/スイス・イン・ラダミスii号",
    "permanent": true
  },
  {
    "source": "/m-s-nubian-sea-lake-nasser-cruise",
    "destination": "/nile-cruises/m-s-nubian-sea-lake-nasser-cruise",
    "permanent": true
  },
  {
    "source": "/es/m-s-mar-nubio-lago-nasser",
    "destination": "/es/nile-cruises/m-s-mar-nubio-lago-nasser",
    "permanent": true
  },
  {
    "source": "/ja/m-s-ヌビアン・シー・レイク・ナセル",
    "destination": "/ja/nile-cruises/m-s-ヌビアン・シー・レイク・ナセル",
    "permanent": true
  },
  {
    "source": "/why-choose-us",
    "destination": "/about",
    "permanent": true
  }
];
